- name: download consul-template
  get_url:
    url: https://releases.hashicorp.com/consul-template/0.23.0/consul-template_0.23.0_linux_amd64.zip
    dest: /tmp/consul-template_0.23.0_linux_amd64.zip

- name: extract consul-template
  unarchive:
    src: /tmp/consul-template_0.23.0_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
