- name: set httpd_can_network_connect flag
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

- name: redis container
  docker_container:
    name: redis
    image: docker.io/redis
    state: started
    recreate: yes
    ports:
      - 6379

- name: apache httpd
  docker_container:
    name: httpd
    image: docker.io/httpd
    state: started
    ports:
      - 80
